name: Deploy to Pages

on:
  push:
    branches: ['master']
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  setup-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Github Pages
        uses: actions/configure-pages@v1

  create-artifact:
    runs-on: ubuntu-latest

    # Read-only permissions for GITHUB_TOKEN
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './'

  deploy:
    # Add a dependency to the artifact job
    needs: create-artifact

    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
